sudo: false

language: java
jdk: oraclejdk8

services:
    - docker
  
before_script:
    - DISPLAY=:0
    - echo $DISPLAY
    - $ip=192.168.99.100
    - xhost + $ip
    - xinit

    
before_install:
    - docker pull bhntools/docker-netbeans
    - docker run -ti --rm \
           -e DISPLAY=$DISPLAY \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -v `pwd`/.netbeans-docker:/home/developer/.netbeans \
           -v `pwd`:/workspace \
           bhntools/docker-netbeans

script:
    - mvn clean verify

